In [4]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
#데이터 

In [5]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y_ori = iris.data , iris.target

In [8]:
#데이터 가공 - 원핫인코딩 
from tensorflow.keras.utils import to_categorical
y = to_categorical(y_ori, 3)

#3 : class의 개수 (세토사,버지니카,버시컬러)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
#학습

In [12]:
# 신경망을 어떻게 쌓을것인가

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=8, input_dim=4, 
                kernel_initializer='uniform',
                activation='relu'))
model.add(Dense(units=3, 
                activation='softmax',
                ))
#신경망 모델 제안(층을 이어서 타이핑한 순서대로 쌓음)
#model.add : 두개의 층 쌓음

#첫번째 층 : 노드개수 8개, 입력노드개수 4개(feature개수와 동일),relu함수 이용하여 활성화 

#입력층 1, 은닉층 1, 출력층 1

In [13]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X_train, y_train,
         epochs = 100,
         batch_size = 1,
         verbose=2)

Epoch 1/100
105/105 - 66s - loss: 1.0527 - accuracy: 0.3714
Epoch 2/100
105/105 - 0s - loss: 1.0082 - accuracy: 0.6095
Epoch 3/100
105/105 - 0s - loss: 0.9481 - accuracy: 0.6952
Epoch 4/100
105/105 - 0s - loss: 0.8811 - accuracy: 0.6952
Epoch 5/100
105/105 - 0s - loss: 0.8108 - accuracy: 0.6952
Epoch 6/100
105/105 - 0s - loss: 0.7440 - accuracy: 0.6952
Epoch 7/100
105/105 - 0s - loss: 0.6809 - accuracy: 0.6952
Epoch 8/100
105/105 - 0s - loss: 0.6312 - accuracy: 0.6952
Epoch 9/100
105/105 - 0s - loss: 0.5903 - accuracy: 0.6952
Epoch 10/100
105/105 - 0s - loss: 0.5517 - accuracy: 0.6952
Epoch 11/100
105/105 - 0s - loss: 0.5192 - accuracy: 0.7143
Epoch 12/100
105/105 - 0s - loss: 0.4933 - accuracy: 0.7048
Epoch 13/100
105/105 - 0s - loss: 0.4665 - accuracy: 0.7333
Epoch 14/100
105/105 - 0s - loss: 0.4487 - accuracy: 0.7524
Epoch 15/100
105/105 - 0s - loss: 0.4274 - accuracy: 0.7714
Epoch 16/100
105/105 - 0s - loss: 0.4112 - accuracy: 0.8476
Epoch 17/100
105/105 - 0s - loss: 0.3963 - accur

In [16]:
hist = model.fit(X_train, y_train , 
                epochs = 100,
                batch_size = 1,
                verbose=0)

In [ ]:
#학습용 데이터의 손실과 정확도

In [17]:
hist.history['accuracy']

[0.9714285731315613,
 0.9809523820877075,
 0.9714285731315613,
 0.9809523820877075,
 0.9809523820877075,
 0.961904764175415,
 0.9714285731315613,
 0.9523809552192688,
 0.9809523820877075,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.961904764175415,
 0.9523809552192688,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9523809552192688,
 0.9809523820877075,
 0.9809523820877075,
 0.961904764175415,
 0.961904764175415,
 0.9904761910438538,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9809523820877075,
 0.961904764175415,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9809523820877075,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9904761910438538,
 0

In [18]:
hist.history['loss']

[0.07834073901176453,
 0.07480166852474213,
 0.06982976943254471,
 0.06784993410110474,
 0.07471571117639542,
 0.07480721920728683,
 0.07286759465932846,
 0.0782165378332138,
 0.07287468016147614,
 0.0768534317612648,
 0.07211373746395111,
 0.07220782339572906,
 0.06875597685575485,
 0.07279349118471146,
 0.07551934570074081,
 0.06979402154684067,
 0.0660761296749115,
 0.08054754883050919,
 0.07008713483810425,
 0.06813858449459076,
 0.06553837656974792,
 0.07563374936580658,
 0.06807710230350494,
 0.06623802334070206,
 0.07267244160175323,
 0.06744195520877838,
 0.06433691829442978,
 0.07306204736232758,
 0.06880763173103333,
 0.06662127375602722,
 0.06590190529823303,
 0.06598777323961258,
 0.06277072429656982,
 0.06747716665267944,
 0.06817719340324402,
 0.06523112207651138,
 0.06375706195831299,
 0.06392183899879456,
 0.0629039853811264,
 0.06471911072731018,
 0.06937454640865326,
 0.06283740699291229,
 0.06405556201934814,
 0.06422441452741623,
 0.06333420425653458,
 0.06701975315

In [ ]:
#평가

In [19]:
loss, acc = model.evaluate(X_test, y_test)

2/2 [==============================] - 2s 6ms/step - loss: 0.0720 - accuracy: 0.9778


In [20]:
#test 데이터의 손실과 정확도
print("손실값:",round(loss,3))
print("정확도:",round(acc,3))

손실값: 0.072
정확도: 0.978


In [ ]:
#주어진 데이터에 대해 과대적합이 아님
#--> test데이터에서의 정확도가 train에서의 정확도보다 높게 나옴 

In [ ]:
#임의의 데이터에 대해 모형출력 확인

In [21]:
from numpy.random import random
from numpy import round

X_new = round(random([3,4])*10, 2)
print(X_new)

#[3,4]: 3행 4열 배열을 만들기 
#0이상 1 미만
#4개 feature - 붓꽃
#이데이터를 넣어서 확인해보는 것

[[7.39 7.91 7.99 1.67]
 [5.56 4.01 4.19 4.29]
 [8.17 4.95 0.48 7.75]]


In [22]:
y_pred = model.predict(X_new)
print(y_pred)

#한 라인이 하나의 데이터에 대한 soft max 결과
#첫번째 붓꽃에서 0번레이블(클래스)일 확률 (8.3212894e-09)
#첫번째 붓꽃에서는 1번 클래스 

#두번째 붓꽃
#0번클래스 

#3번째 - 2번클래스 

[[8.3212894e-09 9.9967170e-01 3.2833876e-04]
 [3.2099857e-13 3.8710563e-04 9.9961287e-01]
 [2.5941140e-14 1.7026190e-04 9.9982965e-01]]


In [23]:
#클래스 정보
y_pred_class = model.predict_classes(X_new)
print(y_pred_class)

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[1 2 2]
