In [1]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

In [2]:
mnist = fetch_openml('mnist_784', version = 1)
X = mnist.data
y_ori = mnist.target.astype(np.int)
#00111문자열을 정수타입으로 바꿔줌
y = to_categorical(y_ori, 10)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

In [4]:
#레이어 쌓기
model = Sequential()
model.add(Dense(input_dim = 28*28, units =20, activation='relu'))
model.add(Dense(units = 15 , activation = 'relu'))
model.add(Dense(units = 10, activation='softmax'))

In [6]:
model.compile(loss='categorical_crossentropy', 
              optimizer=Adam(learning_rate =0.001),
              metrics=['accuracy'])
#손실함수,계산,함수는 뭐로하지?
#Adam()  --> optimizer = 'adam'이랑 같음 / ()안에 값 넣어줄것

In [7]:
#학습
hist = model.fit(X_train, y_train , epochs=10,  batch_size =100, verbose=2,
         validation_data = (X_test, y_test))
#validation_data : 학습을 하면서 별도 검증용 데이터 넣어서 정확도 확인할 수 있음
#--> 과대적합인지 볼 수 있음
#훈련 손실값, 훈련 정확도, 검증 손실값, 검증 정확도 

Epoch 1/10
490/490 - 70s - loss: 2.6339 - accuracy: 0.2276 - val_loss: 1.8220 - val_accuracy: 0.3380
Epoch 2/10
490/490 - 3s - loss: 1.6040 - accuracy: 0.3696 - val_loss: 1.5026 - val_accuracy: 0.3992
Epoch 3/10
490/490 - 3s - loss: 1.3623 - accuracy: 0.4684 - val_loss: 1.2444 - val_accuracy: 0.5413
Epoch 4/10
490/490 - 3s - loss: 1.0518 - accuracy: 0.6379 - val_loss: 0.9866 - val_accuracy: 0.6580
Epoch 5/10
490/490 - 3s - loss: 0.7759 - accuracy: 0.7486 - val_loss: 0.6967 - val_accuracy: 0.8081
Epoch 6/10
490/490 - 3s - loss: 0.5727 - accuracy: 0.8379 - val_loss: 0.5276 - val_accuracy: 0.8569
Epoch 7/10
490/490 - 3s - loss: 0.4068 - accuracy: 0.8866 - val_loss: 0.3818 - val_accuracy: 0.9042
Epoch 8/10
490/490 - 3s - loss: 0.3213 - accuracy: 0.9122 - val_loss: 0.3297 - val_accuracy: 0.9117
Epoch 9/10
490/490 - 4s - loss: 0.2727 - accuracy: 0.9231 - val_loss: 0.3034 - val_accuracy: 0.9191
Epoch 10/10
490/490 - 3s - loss: 0.2470 - accuracy: 0.9299 - val_loss: 0.2937 - val_accuracy: 0.922

In [ ]:
#훈련데이터 accuracy: 0.9299
#검증데이터:0.9225 --> 비슷 : 과대적합 아님

In [8]:
#평가
loss, acc = model.evaluate(X_test, y_test)
print(loss)
print(acc)
#훈련데이터, 테스트데이터 -> 비슷 ->오버피팅이 아님 

657/657 [==============================] - 7s 9ms/step - loss: 0.2937 - accuracy: 0.9225
0.29372909665107727
0.9224761724472046


In [9]:
#예측값 - 얼마나 잘 떨어지는지
#confusion matrix가지고 
#완전한 임의데이터 아님 

y_pred = model.predict(X_test)
y_pred_class = model.predict_classes(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [10]:
y_test_class = np.argmax(y_test, axis=1)


#y_ori =>2
#y =[0,0,1,0,0,0,0,0,0,0] 데이터 이렇게 생김
#그 최댓값이 어느위치에 있는지?
# 위치: 2
#axis =1 : 한 행 안에서 열단위(열을 바꿔가며)로 찾음
#np.argmax(y_test,axis=1)=>2

In [15]:
#confusion matrix
print(confusion_matrix(y_test_class,y_pred_class))


[[1996    1    7    2   16    6   26    3   18    1]
 [   2 2309   26   11    1    0    1   10   26    4]
 [  16   12 1944   20   17    4   32    8   66    5]
 [   4    7   43 1875    1  118    3   18   48   48]
 [   1    4   11    1 1859    9   65   15   22   76]
 [  43    1   10   53   10 1664   54    0   53   35]
 [  15    0   11    0   15    3 1940    3   12    0]
 [   8   13   12    8   41    5    1 2014    8   46]
 [  22   11   17    6   15   23   31    1 1894   28]
 [   5    5    1    9   75   35    2   32   15 1877]]


In [ ]:
#optimizer = "adam"
#optimizer = "sgd"
#optimizer = "rmsprop"

from keras.optimizers import 
#dir(keras.optimizers) --> 최적화 기법들

#optimizer = Adam()
#optimizer = SGD()
#optimizer = RMSprop()

#help(SGD) :SGD() 안에 인자 무엇있는지