# 심층신경망
 ## - 케라스의 신경망 학습 수행

## 케라스(Keras), 텐서플로우 import 

In [1]:
import tensorflow as tf
from tensorflow import keras
#keras.__version__
#help(keras)

## 1) 데이터 준비

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y_ori = iris.data , iris.target

In [4]:
# 데이터 가공 
# 클래스 정보 변환 - 원핫인코딩 

#from sklearn.preprocessing import OneHOtEncoder
from tensorflow.keras.utils import to_categorical
y = to_categorical(y_ori, 3)

#3 : class의 개수 (세토사,버지니카,버시컬러)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

## 2) 인공 신경망 모형 구성
- Sequential()
- Dense()
- add()

In [9]:
# 신경망을 어떻게 쌓을것인가

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

#은닉층 생성
model.add(Dense(units=8, input_dim=4, 
                kernel_initializer='uniform',
                activation='relu'))

#출력층 생성 
model.add(Dense(units=3, 
                activation='softmax',
                ))

In [7]:
#신경망 모델 제안(층을 이어서 타이핑한 순서대로 쌓음)
#model.add : 두개의 층 쌓음

#첫번째 층 : 노드개수 8개, 입력노드개수 4개(feature개수와 동일),relu함수 이용하여 활성화 

#입력층 1, 은닉층 1, 출력층 1

## 3) 모형의 학습 과정에 대한 설정
- compile()

In [10]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [ ]:
#loss : 손실함수 (다중 클래스 분류 교차 엔트로피)
#optimizer : 경사하강법 - 가중치 최적화 알고리즘
#metrics : 모델 성능 평가 지표 

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


## 4) 모형 학습

In [13]:
model.fit(X_train, y_train,
         epochs = 100,
         batch_size = 1,
         verbose=2)

# epochs : 학습 반복 횟수
# verbose : 학습 경과 출력

Epoch 1/100
105/105 - 27s - loss: 1.0418 - accuracy: 0.6286
Epoch 2/100
105/105 - 0s - loss: 0.9766 - accuracy: 0.6952
Epoch 3/100
105/105 - 0s - loss: 0.9071 - accuracy: 0.6952
Epoch 4/100
105/105 - 0s - loss: 0.8325 - accuracy: 0.6952
Epoch 5/100
105/105 - 0s - loss: 0.7674 - accuracy: 0.6952
Epoch 6/100
105/105 - 0s - loss: 0.7006 - accuracy: 0.6952
Epoch 7/100
105/105 - 0s - loss: 0.6480 - accuracy: 0.6952
Epoch 8/100
105/105 - 0s - loss: 0.6046 - accuracy: 0.6952
Epoch 9/100
105/105 - 0s - loss: 0.5610 - accuracy: 0.7048
Epoch 10/100
105/105 - 0s - loss: 0.5279 - accuracy: 0.7143
Epoch 11/100
105/105 - 0s - loss: 0.4994 - accuracy: 0.7619
Epoch 12/100
105/105 - 0s - loss: 0.4690 - accuracy: 0.7524
Epoch 13/100
105/105 - 0s - loss: 0.4473 - accuracy: 0.8286
Epoch 14/100
105/105 - 0s - loss: 0.4263 - accuracy: 0.8571
Epoch 15/100
105/105 - 0s - loss: 0.4057 - accuracy: 0.8762
Epoch 16/100
105/105 - 0s - loss: 0.3880 - accuracy: 0.8952
Epoch 17/100
105/105 - 0s - loss: 0.3737 - accur

In [14]:
hist = model.fit(X_train, y_train , 
                epochs = 100,
                batch_size = 1,
                verbose=0)

train(학습) 데이터의 손실과 정확도 변화 확인
- history 객체

In [15]:
#훈련 정확도
hist.history['accuracy']

[0.9714285731315613,
 0.961904764175415,
 0.9809523820877075,
 0.961904764175415,
 0.9809523820877075,
 0.9714285731315613,
 0.9904761910438538,
 0.9714285731315613,
 0.9714285731315613,
 0.9809523820877075,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.961904764175415,
 0.961904764175415,
 0.9714285731315613,
 0.9809523820877075,
 0.961904764175415,
 0.9809523820877075,
 0.9714285731315613,
 0.9809523820877075,
 0.9714285731315613,
 0.961904764175415,
 0.9714285731315613,
 0.9809523820877075,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.9714285731315613,
 0.961904764175415,
 0.9809523820877075,
 0.961904764175415,
 0.9714285731315613,
 0.961904764175415,
 0.9809523820877075,
 0.9809523820877075,
 0.961904764175415,
 0.9

In [16]:
#훈련 손실값
hist.history['loss']

[0.07948096096515656,
 0.0778311938047409,
 0.07594924420118332,
 0.08209751546382904,
 0.07628172636032104,
 0.07792388647794724,
 0.07238038629293442,
 0.07823333889245987,
 0.07412980496883392,
 0.07495829463005066,
 0.07736793160438538,
 0.07649248093366623,
 0.07568293809890747,
 0.07516101747751236,
 0.07452449947595596,
 0.07500141113996506,
 0.07204537093639374,
 0.071263387799263,
 0.0711769387125969,
 0.0727560967206955,
 0.069392628967762,
 0.07081976532936096,
 0.07759395241737366,
 0.06793425977230072,
 0.07060353457927704,
 0.06792043894529343,
 0.06893393397331238,
 0.06795452535152435,
 0.06853438913822174,
 0.0714881420135498,
 0.07172758132219315,
 0.06840348243713379,
 0.06999237835407257,
 0.07069151848554611,
 0.06754697114229202,
 0.06614790111780167,
 0.06856333464384079,
 0.06714353710412979,
 0.0674428790807724,
 0.06584446132183075,
 0.06824846565723419,
 0.06474430114030838,
 0.06576034426689148,
 0.06654603779315948,
 0.06533176451921463,
 0.0649133846163749

## 5) 모형의 성능 평가
- evaluate()

In [17]:
loss, acc = model.evaluate(X_test, y_test)

2/2 [==============================] - 1s 9ms/step - loss: 0.0819 - accuracy: 0.9778


In [18]:
#test 데이터의 손실과 정확도
print("손실값:",round(loss,3))
print("정확도:",round(acc,3))

손실값: 0.082
정확도: 0.978


In [ ]:
#주어진 데이터에 대해 과대적합이 아님
#--> test데이터에서의 정확도가 train에서의 정확도보다 높게 나옴 
#loss, acc = model.evaluate(X_train, y_train)

## 6) 임의의 데이터에 대해 모형출력 확인

In [34]:
from numpy.random import random
from numpy import round

#임의 데이터 직접 생성
X_new = round(random([3,4])*10, 2)
print(X_new)

#[3,4]: 3행 4열 배열을 만들기 
#0이상 1 미만
#4개 feature - 붓꽃
#이데이터를 넣어서 확인해보는 것

[[8.39 4.43 0.51 0.01]
 [9.05 3.91 1.34 2.95]
 [5.15 1.49 5.35 8.76]]


In [35]:
y_pred = model.predict(X_new)
print(y_pred)

#결과 - 한 라인이 하나의 데이터에 대한 추정된 확률(soft max 점수)

#첫번째 붓꽃에서 0번레이블(클래스)일 확률 (8.3212894e-09)
#첫번째 붓꽃은 2번 클래스 (확률이 제일 높음)

#두번째 붓꽃 - 1번클래스 

#3번째 - 2번클래스 

[[1.0000000e+00 3.7125456e-08 2.9198462e-27]
 [3.7114643e-02 9.6288532e-01 5.2520774e-09]
 [1.8200203e-35 2.3056643e-08 1.0000000e+00]]


In [36]:
#클래스 정보
y_pred_class = model.predict_classes(X_new)
print(y_pred_class)

[0 1 2]
